# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1119acdefad6ab7c0ac7bfa85f02d8834df7555550747ab15bf03573612bbc95056804ea4b1aebca36111c64bb4fd14948abcd9cdc1e53f926d6a01f965d6a11

test:
  secret_key_base: 5dc24d8611ba4d727f055dca1293b7afafce9495d65e28a25dd12aee11e923f33b61036dc20df22a9f97ea49700e76ff379c575fde6fdf353473d4147e321807

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
